// Merge duplicated HMBA Basal Ganglia cell-set nodes.
//
// bgo-full.owl asserts every one of the 113 BG cell sets twice, under two ID bases:
//   https://purl.brain-bican.org/ontology/CS20250428/CS20250428_GROUP_0052   (CAS taxonomy export; BG: curie)
//   https://purl.brain-bican.org/ontology/CCN20250428/CS20250428_GROUP_0052  (bgo ontology build)
// The accessions are identical -- only the base differs -- so the two copies load as
// separate nodes and the properties/edges split between them:
//   CS base  : has_labelset, cell_ontology_term, marker_gene_evidence, rationale_dois,
//              synonyms, incoming :annotations from the taxonomy individual, and the
//              BG2WMB skos mappings generated by this repo
//   CCN base : prefLabel, cluster id (CLM:0010005), accession_*/color_hex_*/tokens_*, and
//              all 178 incoming :has_exemplar_data edges from the CL/PCL cell-type classes
//              -- which are what carry CLM:0010001 soma locations and CLM:0010003 marker sets
// Net effect without this merge: you cannot traverse from a BG: cell set to its cell type's
// locations or markers.
//
// The real fix is upstream in Cellular-Semantics/hmba_basal_ganglia_ontology (one base for
// both producers). Until that lands, merge here, keeping the CS-based node -- the one that
// carries the BG: curie from the curie_map -- as the survivor.
//
// Idempotent: after merging, no CCN20250428 nodes remain, so re-runs match nothing.
// Note there are no indexes on this KB (index: false in neo4j2owl-config.yaml), so the
// iri lookups are scans; that is fine at this graph size and this runs once per build.

MATCH (ccn) WHERE ccn.iri STARTS WITH 'https://purl.brain-bican.org/ontology/CCN20250428/'
WITH ccn, last(split(ccn.iri, '/')) AS accession
MATCH (cs) WHERE cs.iri = 'https://purl.brain-bican.org/ontology/CS20250428/' + accession
// Collect all pairs before mutating, so the merges do not run against a graph that is
// changing underneath the MATCH.
WITH collect({cs: cs, ccn: ccn, cs_props: properties(cs)}) AS pairs
UNWIND pairs AS pair
CALL apoc.refactor.mergeNodes([pair.cs, pair.ccn], {properties: 'combine', mergeRels: true})
  YIELD node
// 'combine' turns every property the two copies disagree on (iri, label, prefLabel, ...)
// into a two-element list. Restore the CS values authoritatively; CCN-only properties are
// left in place.
SET node += pair.cs_props
RETURN count(node) AS merged_bg_cell_sets
;
